
# AUTH
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

api_login_check:
    path: /api/login_check


# APIs
mofi_task:
    type: rest
    resource: "@MofiTaskBundle/Resources/config/routing.yml"
    prefix:   /api/v1

# APPLICATION
app:
    resource: "@AppBundle/Controller/"
    type:     annotation


# DOCS
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/v1/doc


