fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

mofi_task:
    type: rest
    resource: "@MofiTaskBundle/Resources/config/routing.yml"
    prefix:   /api/v1

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
