# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    # Services (FOS User Update - @http://stackoverflow.com/questions/35027683/non-existent-service-fos-user-doctrine-registry)
    fos_user.doctrine_registry:
        alias: doctrine

#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    admin.category:
        class: AppBundle\Admin\CategoryAdmin
        arguments: [~, AppBundle\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Category }

    admin.blog_post:
        class: AppBundle\Admin\BlogPostAdmin
        arguments: [~, AppBundle\Entity\BlogPost, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Blog Post }

#    admin.users:
#        class: AppBundle\Admin\UserAdmin
#        arguments: [~, AppBundle\Entity\User, ~]
#        tags:
#            - { name: sonata.admin, manager_type: orm, label: Users }
#
#

